common_args:
  training_type: "simulation"
  random_seed: 2

data_args:
  dataset: "CRCK"
  data_cache_dir: ~/fedml_data
  trainset: /shared/dqwang/datasets/CRC/CRC_DX_train
  testset: /shared/dqwang/datasets/CRC/CRC_DX_test
  client_anno: /shared/dqwang/datasets/CRC/annotation/federate/split_5_1
  train_anno: /shared/dqwang/datasets/CRC/annotation/train_ann.txt
  test_anno: /shared/dqwang/datasets/CRC/annotation/test_ann.txt
  task: 0

model_args:
  model: "resnet18"

train_args:
  federated_optimizer: "FedProx"
  client_id_list: "[]"
  client_num_in_total: 5
  client_num_per_round: 5
  comm_round: 20
  epochs: 10
  batch_size: 256
  client_optimizer: sgd
  learning_rate: 0.001
  weight_decay: 0.0001
  fedprox_mu: 1

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 2

comm_args:
  backend: "sp"
  is_mobile: 0

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: True
  wandb_key: 9dc9b69092ccf64b8320cb69022292b51da4be84
  wandb_entity: zlt
  wandb_project: fedml_fedprox
  run_name: fedml_torch_fedprox_crck0_res18_s2